version: 2.1
jobs:
  deploy:
    docker:
      - image: rymdkraftverk/ci:latest
    steps:
      - checkout
      - run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/rkv-backend.git master
workflows:
  default:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
